# Generated by Django 5.1.15 on 2026-07-13 17:32

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_alter_optiongroup_visibility_productcomposition'),
        ('companies', '0001_initial'),
        ('orders', '0002_orderitemoption_quantity'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderItemComponent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product_name', models.CharField(max_length=200)),
                ('base_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('order_item', models.ForeignKey(db_column='order_item_id', on_delete=django.db.models.deletion.CASCADE, related_name='components', to='orders.orderitem')),
                ('product', models.ForeignKey(blank=True, db_column='product_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_item_components', to='catalog.product')),
                ('tenant', models.ForeignKey(db_column='tenant_id', on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='companies.company')),
            ],
            options={
                'db_table': 'order_item_components',
                'ordering': ['sort_order'],
                'indexes': [models.Index(fields=['order_item'], name='order_item__order_i_12ca54_idx')],
            },
        ),
    ]
