# Generated by Django 5.1.15 on 2026-07-07 11:25

import uuid
from decimal import Decimal

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models

import apps.companies.domain.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('subdomain', models.CharField(max_length=63, unique=True, validators=[apps.companies.domain.validators.validate_subdomain])),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('legal_name', models.CharField(max_length=255)),
                ('trade_name', models.CharField(max_length=255)),
                ('document', models.CharField(blank=True, max_length=18, null=True)),
                ('email', models.EmailField(max_length=254, validators=[django.core.validators.EmailValidator()])),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('status', models.CharField(choices=[('active', 'Ativa'), ('inactive', 'Inativa'), ('suspended', 'Suspensa'), ('trial', 'Trial')], db_index=True, default='active', max_length=20)),
                ('logo_url', models.URLField(blank=True, max_length=500, null=True)),
                ('cover_url', models.URLField(blank=True, max_length=500, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('timezone', models.CharField(default='America/Sao_Paulo', max_length=50)),
            ],
            options={
                'db_table': 'companies',
                'ordering': ['trade_name'],
            },
        ),
        migrations.CreateModel(
            name='BusinessHours',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('day_of_week', models.PositiveSmallIntegerField()),
                ('opens_at', models.TimeField()),
                ('closes_at', models.TimeField()),
                ('is_closed', models.BooleanField(default=False)),
                ('tenant', models.ForeignKey(db_column='tenant_id', on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='companies.company')),
            ],
            options={
                'db_table': 'business_hours',
                'ordering': ['day_of_week'],
                'constraints': [models.UniqueConstraint(fields=('tenant', 'day_of_week'), name='uniq_business_hours_tenant_day'), models.CheckConstraint(condition=models.Q(('day_of_week__gte', 0), ('day_of_week__lte', 6)), name='business_hours_valid_day')],
            },
        ),
        migrations.CreateModel(
            name='CompanySettings',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('min_order_value', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10)),
                ('delivery_fee', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10)),
                ('free_delivery_above', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('estimated_prep_time', models.PositiveIntegerField(default=30)),
                ('estimated_delivery_time', models.PositiveIntegerField(default=45)),
                ('accepts_delivery', models.BooleanField(default=True)),
                ('accepts_pickup', models.BooleanField(default=True)),
                ('accepts_dine_in', models.BooleanField(default=False)),
                ('is_open', models.BooleanField(default=True)),
                ('auto_close_outside_hours', models.BooleanField(default=True)),
                ('payment_methods', models.JSONField(default=list)),
                ('delivery_areas', models.JSONField(blank=True, null=True)),
                ('theme', models.JSONField(blank=True, null=True)),
                ('notification_settings', models.JSONField(blank=True, null=True)),
                ('tenant', models.ForeignKey(db_column='tenant_id', on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='companies.company')),
            ],
            options={
                'db_table': 'company_settings',
                'constraints': [models.UniqueConstraint(fields=('tenant',), name='uniq_company_settings_tenant')],
            },
        ),
    ]
