# Generated by Django 5.1.15 on 2026-07-22 16:11

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0003_companysettings_delivery_city'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommunicationConnection',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('channel', models.CharField(choices=[('whatsapp', 'WhatsApp'), ('email', 'Email'), ('sms', 'SMS')], default='whatsapp', max_length=20)),
                ('provider_key', models.CharField(choices=[('evolution', 'Evolution'), ('meta_cloud', 'Meta Cloud'), ('zapi', 'Z-API'), ('fake', 'Fake (testes)')], default='evolution', max_length=40)),
                ('role', models.CharField(choices=[('default', 'Padrão'), ('delivery', 'Delivery'), ('finance', 'Financeiro'), ('support', 'Suporte'), ('store', 'Loja física')], default='default', max_length=20)),
                ('display_name', models.CharField(blank=True, default='', max_length=120)),
                ('phone_e164', models.CharField(blank=True, default='', max_length=20)),
                ('phone_display', models.CharField(blank=True, default='', max_length=30)),
                ('status', models.CharField(choices=[('pending', 'Pendente'), ('awaiting_qr', 'Aguardando QR'), ('connected', 'Conectado'), ('disconnected', 'Desconectado'), ('error', 'Erro')], default='pending', max_length=20)),
                ('credentials_signed', models.TextField(blank=True, default='')),
                ('provider_metadata', models.JSONField(blank=True, default=dict)),
                ('last_health_at', models.DateTimeField(blank=True, null=True)),
                ('last_health_status', models.JSONField(blank=True, default=dict)),
                ('last_error_code', models.CharField(blank=True, default='', max_length=40)),
                ('tenant', models.ForeignKey(db_column='tenant_id', on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='companies.company')),
            ],
            options={
                'db_table': 'communication_connections',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MerchantAlert',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('kind', models.CharField(max_length=60)),
                ('severity', models.CharField(choices=[('info', 'Info'), ('warning', 'Aviso'), ('critical', 'Crítico')], default='warning', max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('body', models.TextField(blank=True, default='')),
                ('action_hint', models.CharField(blank=True, default='', max_length=200)),
                ('is_read', models.BooleanField(default=False)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('connection', models.ForeignKey(blank=True, db_column='connection_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='communications.communicationconnection')),
                ('tenant', models.ForeignKey(db_column='tenant_id', on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='companies.company')),
            ],
            options={
                'db_table': 'merchant_alerts',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MessageTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('channel', models.CharField(choices=[('whatsapp', 'WhatsApp'), ('email', 'Email'), ('sms', 'SMS')], default='whatsapp', max_length=20)),
                ('event_key', models.CharField(max_length=60)),
                ('body', models.TextField()),
                ('is_system_seed', models.BooleanField(default=True)),
                ('tenant', models.ForeignKey(db_column='tenant_id', on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='companies.company')),
            ],
            options={
                'db_table': 'message_templates',
            },
        ),
        migrations.CreateModel(
            name='MessageDispatch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('channel', models.CharField(choices=[('whatsapp', 'WhatsApp'), ('email', 'Email'), ('sms', 'SMS')], default='whatsapp', max_length=20)),
                ('event_key', models.CharField(blank=True, default='', max_length=60)),
                ('status', models.CharField(choices=[('pending', 'Pendente'), ('queued', 'Na fila'), ('sent', 'Enviada'), ('delivered', 'Entregue'), ('failed', 'Falhou'), ('test', 'Teste')], default='pending', max_length=20)),
                ('recipient', models.CharField(blank=True, default='', max_length=40)),
                ('body_snapshot', models.TextField(blank=True, default='')),
                ('provider_message_id', models.CharField(blank=True, default='', max_length=120)),
                ('error_code', models.CharField(blank=True, default='', max_length=40)),
                ('error_message', models.TextField(blank=True, default='')),
                ('idempotency_key', models.CharField(blank=True, default='', max_length=120)),
                ('payload_snapshot', models.JSONField(blank=True, default=dict)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('latency_ms', models.PositiveIntegerField(blank=True, null=True)),
                ('is_test', models.BooleanField(default=False)),
                ('connection', models.ForeignKey(blank=True, db_column='connection_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dispatches', to='communications.communicationconnection')),
                ('tenant', models.ForeignKey(db_column='tenant_id', on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='companies.company')),
                ('template', models.ForeignKey(blank=True, db_column='template_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dispatches', to='communications.messagetemplate')),
            ],
            options={
                'db_table': 'message_dispatches',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SituationSetting',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('channel', models.CharField(choices=[('whatsapp', 'WhatsApp'), ('email', 'Email'), ('sms', 'SMS')], default='whatsapp', max_length=20)),
                ('event_key', models.CharField(max_length=60)),
                ('is_enabled', models.BooleanField(default=True)),
                ('connection', models.ForeignKey(blank=True, db_column='connection_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='situation_settings', to='communications.communicationconnection')),
                ('tenant', models.ForeignKey(db_column='tenant_id', on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='companies.company')),
            ],
            options={
                'db_table': 'communication_situation_settings',
            },
        ),
        migrations.AddIndex(
            model_name='communicationconnection',
            index=models.Index(fields=['tenant', 'channel', 'status'], name='comm_conn_tenant_ch_st'),
        ),
        migrations.AddConstraint(
            model_name='communicationconnection',
            constraint=models.UniqueConstraint(fields=('tenant', 'channel', 'role'), name='uniq_comm_conn_tenant_channel_role'),
        ),
        migrations.AddIndex(
            model_name='merchantalert',
            index=models.Index(fields=['tenant', 'is_read', 'created_at'], name='malert_tenant_read_cr'),
        ),
        migrations.AddConstraint(
            model_name='messagetemplate',
            constraint=models.UniqueConstraint(fields=('tenant', 'channel', 'event_key'), name='uniq_msg_tpl_tenant_ch_ev'),
        ),
        migrations.AddIndex(
            model_name='messagedispatch',
            index=models.Index(fields=['tenant', 'status', 'created_at'], name='msg_disp_tenant_st_cr'),
        ),
        migrations.AddIndex(
            model_name='messagedispatch',
            index=models.Index(fields=['tenant', 'idempotency_key'], name='msg_disp_tenant_idem'),
        ),
        migrations.AddConstraint(
            model_name='messagedispatch',
            constraint=models.UniqueConstraint(condition=models.Q(('idempotency_key', ''), _negated=True), fields=('tenant', 'idempotency_key'), name='uniq_msg_disp_tenant_idem'),
        ),
        migrations.AddConstraint(
            model_name='situationsetting',
            constraint=models.UniqueConstraint(fields=('tenant', 'channel', 'event_key'), name='uniq_comm_situation_tenant_ch_ev'),
        ),
    ]
