# Generated by Django 5.1.15 on 2026-07-22 10:33

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0008_composition_min_parts_optional'),
        ('companies', '0002_companysettings_setup'),
    ]

    operations = [
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('commercial_goal', models.CharField(choices=[('increase_sales', 'Aumentar vendas'), ('raise_ticket', 'Aumentar ticket'), ('attract_new', 'Atrair novos clientes'), ('bring_back', 'Trazer clientes de volta'), ('sell_category', 'Vender mais de uma categoria'), ('encourage_combo', 'Incentivar combos'), ('order_threshold', 'Pedidos acima de um valor')], default='increase_sales', max_length=40)),
                ('mechanism', models.CharField(choices=[('product_price', 'Preço de produto'), ('bundle', 'Combo'), ('free_shipping', 'Frete grátis'), ('gift', 'Brinde'), ('order_discount', 'Desconto no pedido')], default='product_price', max_length=40)),
                ('status', models.CharField(choices=[('draft', 'Rascunho'), ('active', 'Ativa'), ('paused', 'Pausada'), ('ended', 'Encerrada')], default='active', max_length=20)),
                ('title', models.CharField(blank=True, default='', max_length=200)),
                ('promo_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('reference_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('recurrence_type', models.CharField(choices=[('once', 'Apenas uma vez'), ('daily', 'Todos os dias'), ('weekdays', 'Dias da semana'), ('hours', 'Horários'), ('commemorative', 'Datas comemorativas')], default='once', max_length=20)),
                ('weekdays', models.JSONField(blank=True, default=list)),
                ('starts_at', models.DateTimeField()),
                ('ends_at', models.DateTimeField(blank=True, null=True)),
                ('time_start', models.TimeField(blank=True, null=True)),
                ('time_end', models.TimeField(blank=True, null=True)),
                ('show_on_home', models.BooleanField(default=True)),
                ('show_on_menu', models.BooleanField(default=True)),
                ('show_on_product', models.BooleanField(default=True)),
                ('link_only', models.BooleanField(default=False)),
                ('show_as_banner', models.BooleanField(default=False)),
                ('product', models.ForeignKey(blank=True, db_column='product_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='campaigns', to='catalog.product')),
                ('tenant', models.ForeignKey(db_column='tenant_id', on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='companies.company')),
            ],
            options={
                'db_table': 'campaigns',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['tenant', 'status'], name='campaigns_tenant__d8e2a0_idx'), models.Index(fields=['tenant', 'product', 'status'], name='campaigns_tenant__23d733_idx'), models.Index(fields=['tenant', 'starts_at', 'ends_at'], name='campaigns_tenant__89f162_idx')],
            },
        ),
    ]
