# Generated by Django 5.1.15 on 2026-07-13 17:32

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_product_builder_fields'),
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='optiongroup',
            name='visibility',
            field=models.CharField(choices=[('always', 'Sempre'), ('hidden', 'Oculto'), ('conditional', 'Condicional')], default='always', max_length=20),
        ),
        migrations.CreateModel(
            name='ProductComposition',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_enabled', models.BooleanField(default=False)),
                ('source_type', models.CharField(choices=[('category', 'Mesma categoria'), ('tag', 'Por tag'), ('custom', 'Lista personalizada')], default='category', max_length=20)),
                ('source_tag', models.CharField(blank=True, default='', max_length=50)),
                ('label', models.CharField(blank=True, default='Escolher outro sabor', max_length=80)),
                ('min_parts', models.PositiveIntegerField(default=2)),
                ('max_parts', models.PositiveIntegerField(default=2)),
                ('pricing_rule', models.CharField(choices=[('highest', 'Maior preço'), ('average', 'Média dos preços'), ('main', 'Preço do produto principal')], default='highest', max_length=20)),
                ('custom_products', models.ManyToManyField(blank=True, related_name='composition_memberships', to='catalog.product')),
                ('product', models.OneToOneField(db_column='product_id', on_delete=django.db.models.deletion.CASCADE, related_name='composition', to='catalog.product')),
                ('source_category', models.ForeignKey(blank=True, db_column='source_category_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='composition_sources', to='catalog.category')),
                ('tenant', models.ForeignKey(db_column='tenant_id', on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='companies.company')),
            ],
            options={
                'db_table': 'product_compositions',
                'indexes': [models.Index(fields=['tenant', 'is_enabled'], name='product_com_tenant__c1203d_idx')],
            },
        ),
    ]
