# Generated by Django 5.1.15 on 2026-07-21 12:49

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_alter_optiongroup_visibility_productcomposition'),
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryCapability',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('kind', models.CharField(choices=[('size', 'Tamanhos'), ('crust', 'Bordas'), ('extras', 'Adicionais'), ('buildable', 'Ingredientes'), ('sauces', 'Molhos'), ('dough', 'Massas'), ('volume', 'Volumes'), ('half', 'Meio a meio'), ('other', 'Outro')], max_length=20)),
                ('enabled', models.BooleanField(default=True)),
                ('is_required', models.BooleanField(default=False)),
                ('sort_order', models.IntegerField(default=0)),
                ('settings', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'db_table': 'category_capabilities',
                'ordering': ['sort_order', 'kind'],
            },
        ),
        migrations.CreateModel(
            name='CategoryLibrary',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('kind', models.CharField(choices=[('size', 'Tamanhos'), ('crust', 'Bordas'), ('extras', 'Adicionais'), ('buildable', 'Ingredientes'), ('sauces', 'Molhos'), ('dough', 'Massas'), ('volume', 'Volumes'), ('half', 'Meio a meio'), ('other', 'Outro')], max_length=20)),
                ('sort_order', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'category_libraries',
                'ordering': ['sort_order'],
            },
        ),
        migrations.CreateModel(
            name='CategoryLibraryItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sort_order', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'category_library_items',
                'ordering': ['sort_order'],
            },
        ),
        migrations.CreateModel(
            name='ProductOptionExclusion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'product_option_exclusions',
            },
        ),
        migrations.CreateModel(
            name='ProductOptionPrice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'db_table': 'product_option_prices',
            },
        ),
        migrations.AddField(
            model_name='category',
            name='template_key',
            field=models.CharField(blank=True, default='', max_length=40),
        ),
        migrations.AddField(
            model_name='optiongroup',
            name='kind',
            field=models.CharField(blank=True, choices=[('size', 'Tamanhos'), ('crust', 'Bordas'), ('extras', 'Adicionais'), ('buildable', 'Ingredientes'), ('sauces', 'Molhos'), ('dough', 'Massas'), ('volume', 'Volumes'), ('half', 'Meio a meio'), ('other', 'Outro')], default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='productcomposition',
            name='pricing_rule',
            field=models.CharField(choices=[('highest', 'Maior preço'), ('average', 'Média dos preços'), ('sum', 'Soma dos preços'), ('main', 'Preço do produto principal')], default='highest', max_length=20),
        ),
        migrations.AddIndex(
            model_name='optiongroup',
            index=models.Index(fields=['tenant', 'kind'], name='option_grou_tenant__bc034c_idx'),
        ),
        migrations.AddField(
            model_name='categorycapability',
            name='category',
            field=models.ForeignKey(db_column='category_id', on_delete=django.db.models.deletion.CASCADE, related_name='capabilities', to='catalog.category'),
        ),
        migrations.AddField(
            model_name='categorycapability',
            name='tenant',
            field=models.ForeignKey(db_column='tenant_id', on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='companies.company'),
        ),
        migrations.AddField(
            model_name='categorylibrary',
            name='category',
            field=models.ForeignKey(db_column='category_id', on_delete=django.db.models.deletion.CASCADE, related_name='libraries', to='catalog.category'),
        ),
        migrations.AddField(
            model_name='categorylibrary',
            name='option_group',
            field=models.ForeignKey(db_column='option_group_id', on_delete=django.db.models.deletion.CASCADE, related_name='category_libraries', to='catalog.optiongroup'),
        ),
        migrations.AddField(
            model_name='categorylibrary',
            name='tenant',
            field=models.ForeignKey(db_column='tenant_id', on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='companies.company'),
        ),
        migrations.AddField(
            model_name='categorylibraryitem',
            name='category_library',
            field=models.ForeignKey(db_column='category_library_id', on_delete=django.db.models.deletion.CASCADE, related_name='items', to='catalog.categorylibrary'),
        ),
        migrations.AddField(
            model_name='categorylibraryitem',
            name='option',
            field=models.ForeignKey(db_column='option_id', on_delete=django.db.models.deletion.CASCADE, related_name='category_library_items', to='catalog.option'),
        ),
        migrations.AddField(
            model_name='categorylibraryitem',
            name='tenant',
            field=models.ForeignKey(db_column='tenant_id', on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='companies.company'),
        ),
        migrations.AddField(
            model_name='productoptionexclusion',
            name='option',
            field=models.ForeignKey(db_column='option_id', on_delete=django.db.models.deletion.CASCADE, related_name='product_exclusions', to='catalog.option'),
        ),
        migrations.AddField(
            model_name='productoptionexclusion',
            name='product',
            field=models.ForeignKey(db_column='product_id', on_delete=django.db.models.deletion.CASCADE, related_name='option_exclusions', to='catalog.product'),
        ),
        migrations.AddField(
            model_name='productoptionexclusion',
            name='tenant',
            field=models.ForeignKey(db_column='tenant_id', on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='companies.company'),
        ),
        migrations.AddField(
            model_name='productoptionprice',
            name='option',
            field=models.ForeignKey(db_column='option_id', on_delete=django.db.models.deletion.CASCADE, related_name='product_prices', to='catalog.option'),
        ),
        migrations.AddField(
            model_name='productoptionprice',
            name='product',
            field=models.ForeignKey(db_column='product_id', on_delete=django.db.models.deletion.CASCADE, related_name='option_prices', to='catalog.product'),
        ),
        migrations.AddField(
            model_name='productoptionprice',
            name='tenant',
            field=models.ForeignKey(db_column='tenant_id', on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='companies.company'),
        ),
        migrations.AddIndex(
            model_name='categorycapability',
            index=models.Index(fields=['category', 'sort_order'], name='category_ca_categor_aae8d3_idx'),
        ),
        migrations.AddConstraint(
            model_name='categorycapability',
            constraint=models.UniqueConstraint(fields=('category', 'kind'), name='uniq_category_capability_kind'),
        ),
        migrations.AddIndex(
            model_name='categorylibrary',
            index=models.Index(fields=['category', 'kind'], name='category_li_categor_6abb61_idx'),
        ),
        migrations.AddConstraint(
            model_name='categorylibrary',
            constraint=models.UniqueConstraint(fields=('category', 'option_group'), name='uniq_category_library_group'),
        ),
        migrations.AddConstraint(
            model_name='categorylibraryitem',
            constraint=models.UniqueConstraint(fields=('category_library', 'option'), name='uniq_category_library_option'),
        ),
        migrations.AddIndex(
            model_name='productoptionexclusion',
            index=models.Index(fields=['product'], name='product_opt_product_d61422_idx'),
        ),
        migrations.AddConstraint(
            model_name='productoptionexclusion',
            constraint=models.UniqueConstraint(fields=('product', 'option'), name='uniq_product_option_exclusion'),
        ),
        migrations.AddIndex(
            model_name='productoptionprice',
            index=models.Index(fields=['product'], name='product_opt_product_2fa691_idx'),
        ),
        migrations.AddConstraint(
            model_name='productoptionprice',
            constraint=models.UniqueConstraint(fields=('product', 'option'), name='uniq_product_option_price'),
        ),
        migrations.AddConstraint(
            model_name='productoptionprice',
            constraint=models.CheckConstraint(condition=models.Q(('price__gte', 0)), name='product_option_prices_positive'),
        ),
    ]
