# Generated by Django 5.1.15 on 2026-07-21 14:36

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_category_recipe_phase0'),
        ('companies', '0002_companysettings_setup'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryOptionPrice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('category', models.ForeignKey(db_column='category_id', on_delete=django.db.models.deletion.CASCADE, related_name='option_prices', to='catalog.category')),
                ('option', models.ForeignKey(db_column='option_id', on_delete=django.db.models.deletion.CASCADE, related_name='category_prices', to='catalog.option')),
                ('tenant', models.ForeignKey(db_column='tenant_id', on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='companies.company')),
            ],
            options={
                'db_table': 'category_option_prices',
                'indexes': [models.Index(fields=['category'], name='category_op_categor_4dc43c_idx')],
                'constraints': [models.UniqueConstraint(fields=('category', 'option'), name='uniq_category_option_price'), models.CheckConstraint(condition=models.Q(('price__gte', 0)), name='category_option_prices_positive')],
            },
        ),
    ]
